on: push

jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Run `npm build:production`
        run: npm run-script build:production

  report:
    name: Report stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@master

      - name: Send Velocity deployment
        uses: ./
        with:
          token: ${{ secrets.VELOCITY_DEPLOYMENT_TOKEN }}
- name: Velocity konuşlandırma eylemi
  kullanır: codeclimate/velocity-deploy-action@v1.0.0
